version: '3'

networks:
  mlflow-network:

services:
  mlflow-db:
    container_name: mlflow-db
    image: mysql
    restart: always
    networks:
      - mlflow-network
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_DIR}:/var/lib/mysql
  mlflow:
    container_name: mlflow-tracking-server
    build: ./mlflow
    image: ghcr.io/mlflow/mlflow:v2.5.0
    restart: always
    depends_on:
      - mlflow-db
    ports:
      - ${MLFLOW_PORT}:${MLFLOW_PORT}
      - 5000:5000
    volumes:
      - ${ARTIFACT_DIR}:${ARTIFACT_DIR}
    networks:
      - mlflow-network
    command: >
      mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mlflow-db:3306/${MYSQL_DATABASE} --default-artifact-root file:${ARTIFACT_DIR} --host 0.0.0.0
